# -*- coding: utf-8 -*-
"""RNN.PY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-cLqitaCPQJRZWjBIU3WL6F2ra1xfGR
"""

import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
import matplotlib.pyplot as plt

(x_train, y_train), (x_test, y_test) = mnist.load_data()

train_imag = x_train.reshape((60000, 28, 28)).astype('float32') / 255.0
test_imag = x_test.reshape((10000, 28, 28)).astype('float32') / 255.0

input_shape = (28, 28)

inputs = Input(shape=input_shape)

rnn_layer = LSTM(128, return_sequences=True)(inputs)
rnn_layer = LSTM(64)(rnn_layer)
rnn_layer = Dropout(0.3)(rnn_layer)

outputs = Dense(10, activation='softmax')(rnn_layer)

model = models.Model(inputs=inputs, outputs=outputs)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_imag,
    y_train,
    validation_data=(test_imag, y_test),
    epochs=10
)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'])
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'])
plt.show()

